# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3
   

  tests:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3
    
      - name: Run tests
        run: python tests.py
